"""followers

Revision ID: 106dd44d2ab0
Revises: da8003f598e4
Create Date: 2019-07-19 09:01:25.604734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106dd44d2ab0'
down_revision = 'da8003f598e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
